#!/usr/bin/env php
<?php
$script = array_shift($argv);
$command = 'ssh -q bastion "/vol/ebs1/ahsupport/support_bin/ah ahdc ' . implode(' ', $argv) . '"';
$result=`$command`;
if (preg_match('/^(ssh|rsync)\b/',$result) && !in_array('--pipe',$argv)) {
  passthru($result);
}
else {
  echo $result;
}
