#!/usr/bin/env php
<?php
$script = array_shift($argv);
foreach ($argv as &$tmp_arg) {
  if (preg_match('|\s|', $tmp_arg)) {
    $tmp_arg = '\"' . $tmp_arg . '\"';
  }
}
$command = 'ssh -q bastion "/vol/ebs1/ahsupport/support_bin/ah ahmc ' . implode(' ', $argv) . '"';
$result=`$command`;
if (preg_match('/^(ssh|rsync)\b/',$result) && !in_array('--pipe',$argv)) {
  passthru($result);
}
else {
  echo $result;
}
