#!/usr/bin/php
<?php
    /*
        Install guide:
            ln -s ~/Support-Tools/ratools/mod-audit ~/bin/mod-audit
            #If ~/bin isn't in your path, add this line to your .bash_profile/.profile
            export PATH=$PATH:~/bin
        Usage guide:
            mod-audit @<site>.<enviroment> <ticketnumber>
    */
    if(count($argv) < 3){
        echo "Usage: mod_audit @<site>.<enviroment> <ticketnumber>\n";
        die;
    }
    $repo = exec("aht {$argv[1]} repo");
    $repo_type = "git";
    if(strpos($repo,"git") === false){
        $repo_type = "svn";
    }
    $RA_MAND_UPDATES=explode("|","acquia_connector|acquia_search|mollom|apachesolr|apachesolr_multisitesearch|search_api_acquia|search-api|entity");
    $RA_SUGG_UPDATES="\-dev|\-unstable|\-alpha|\-beta|\-rc";
    $sites = array();
    exec("aht {$argv[1]} sites",$sites);
    $all_updates = array(
        "Security"=>array(),
        "Mandatory"=>array(),
        "Suggested"=>array(),
        "Other"=>array(),
    );
    $sugg_updates = array();
    $other_updates = array();
    foreach($sites as $site){
        if(strpos($site,"Warning:") !== false){
            continue;
        }
        if(strpos($site,"->") !== false){
            $site = preg_replace("/->\s.*$/","",$site);
        }
        $updates = array();
        exec("aht {$argv[1]} drush5 upc --no-core --pipe --uri=$site",$updates);
        $total = count($updates);
        echo "Evaluating $total modules on $site site (0%)";
        for($i=0;$i<$total;++$i){
            $progress = floor(($i/$total)*100);
            echo "\rEvaluating $total modules on $site site ($progress%)";
            $update = $updates[$i];
            if(!preg_match("/^\S*\s\d\.x\S*\s\d\.x\S*\s\S*$/",$update)){
                continue;
            }
            $update = explode(" ", $update);
            if($update[3] == "SECURITY-UPDATE-available"){
                $module = $update[0];
                $all_updates["Security"][] = $update;
            }
            else if(in_array($update[0],$RA_MAND_UPDATES)){
                $module = $update[0];
                $all_updates["Mandatory"][] = $update;
            }
            else if(preg_match("/.*(".$RA_SUGG_UPDATES.").*/",$update[1]) == 1){
                $all_updates["Suggested"][] = $update;
            }
            else{
                $all_updates["Other"][] = $update;
            }
        }
        echo "\rEvaluating $total modules on $site site (100%)";
        echo "\n";
    }
    foreach($all_updates as $name=>$updates){
        if(count($updates) == 0){
            continue;
        }
        $updates = array_unique($updates,SORT_REGULAR);
        echo "---------------------------------------------------------------------------\n";
        echo "$name Updates:\n";
        foreach($updates as $update){
            echo implode($update," ")."\n";
        }
        echo "\n";
        foreach($updates as $update){
            if($update[3] == "SECURITY-UPDATE-available"){
                echo "$repo_type-mupdate-sec {$update[0]} {$update[1]} {$update[2]} {$argv[2]}\n";
            }
            else{
                echo "$repo_type-mupdate {$update[0]} {$update[1]} {$update[2]} {$argv[2]}\n";
            }
        }
    }
    echo "---------------------------------------------------------------------------\n";
?>